# Generated by Django 5.2.17 on 2026-10-06 13:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('burst', 'Many reports from few devices in a short time'), ('far_from_gps', '“Just now” report far from the reporter’s location'), ('text_duplicate', 'Same description as another report'), ('low_trust', 'Reporter has a low trust score')], max_length=24)),
                ('h3', models.CharField(blank=True, db_index=True, max_length=16)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mod_flags', to='incidents.report')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
