# Generated by Django 5.2.17 on 2026-10-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='reason',
            field=models.CharField(choices=[('burst', 'Many reports from few devices in a short time'), ('text_duplicate', 'Same description as another report'), ('low_trust', 'Reporter has a low trust score')], max_length=24),
        ),
    ]
