# Generated by Django 5.2.17 on 2026-10-06 13:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_hash', models.CharField(max_length=64, unique=True)),
                ('trust', models.FloatField(default=0.8)),
                ('reports_count', models.PositiveIntegerField(default=0)),
                ('verified_count', models.PositiveIntegerField(default=0)),
                ('rejected_count', models.PositiveIntegerField(default=0)),
                ('restricted_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('incident', 'Incident'), ('knowledge', 'Knowledge'), ('positive', 'Positive')], max_length=16)),
                ('category', models.CharField(choices=[('motorbike', 'motorbike'), ('rickshaw_cng', 'rickshaw_cng'), ('on_foot', 'on_foot'), ('bus', 'bus'), ('weapon', 'weapon'), ('well_lit', 'well_lit'), ('busy_late', 'busy_late'), ('patrol_seen', 'patrol_seen'), ('cctv', 'cctv')], max_length=24)),
                ('h3', models.CharField(db_index=True, max_length=16)),
                ('date', models.DateField(blank=True, null=True)),
                ('block', models.PositiveSmallIntegerField()),
                ('hour', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('days', models.CharField(blank=True, max_length=16)),
                ('relation', models.CharField(blank=True, max_length=16)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate')], db_index=True, default='pending', max_length=16)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('corroborations', models.PositiveIntegerField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('ip_hash', models.CharField(db_index=True, max_length=64)),
                ('text_fingerprint', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='incidents.device')),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidents.report')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_hash', models.CharField(max_length=64)),
                ('independent', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incidents.device')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='incidents.report')),
            ],
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['h3', 'created_at'], name='incidents_r_h3_763aae_idx'),
        ),
        migrations.AddConstraint(
            model_name='confirmation',
            constraint=models.UniqueConstraint(fields=('report', 'device'), name='one_confirmation_per_device'),
        ),
    ]
