# Generated by Django 5.2.17 on 2026-10-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_alter_confirmation_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
