# Generated by Django 5.2.17 on 2026-10-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_report_is_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='video_public_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='report',
            name='video_status',
            field=models.CharField(blank=True, choices=[('', 'None'), ('awaiting', 'Awaiting'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='', max_length=16),
        ),
    ]
