# Generated by Django 5.2.17 on 2026-10-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_report_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='source',
            field=models.CharField(choices=[('community', 'Community'), ('media', 'Media'), ('official', 'Official')], db_index=True, default='community', max_length=16),
        ),
        migrations.AddField(
            model_name='report',
            name='source_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='report',
            name='source_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
