# Generated by Django 5.2.17 on 2026-10-07 12:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.CharField(max_length=1024, unique=True)),
                ('p256dh', models.CharField(max_length=200)),
                ('auth', models.CharField(max_length=100)),
                ('locale', models.CharField(default='bn', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WatchedArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h3', models.CharField(db_index=True, max_length=16)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='watch.pushsubscription')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('subscription', 'h3'), name='one_watch_per_area')],
            },
        ),
    ]
